name: 🌟 Build and Release Plugin

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-release:
    name: 🛠️ Build Plugin ZIP on Tag
    runs-on: ubuntu-latest
    env:
      PLUGIN_SLUG: revalidate-for-vercel
      RELEASE_TAG: ${{ github.ref_name }}

    steps:
      - name: 💾 Checkout code
        uses: actions/checkout@v3

      - name: 📋 Set up Node (optional)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 🌐 Set environment vars
        run: |
          echo "PLUGIN_SLUG=revalidate-for-vercel" >> $GITHUB_ENV
          echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: 🧹 Clean up files
        run: |
          rm -f build-release.sh
          find . -name ".DS_Store" -delete

      - name: 📁 Prepare build directory
        run: |
          mkdir build
          rsync -av --progress ./ ./build/$PLUGIN_SLUG \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "node_modules" \
            --exclude ".gitignore" \
            --exclude "README.md" \
            --exclude "*.zip" \
            --exclude "readme-wp.txt" \
            --exclude "update-version.sh" \
            --exclude "build-release.sh"

          cp ./readme-wp.txt ./build/$PLUGIN_SLUG/readme.txt

      - name: 🔧 PHP syntax check (lint)
        run: |
          find ./build/$PLUGIN_SLUG -type f -name "*.php" -exec php -l {} \;

      - name: 🔓 Allow Composer Plugin for PHPCS compatibility
        run: composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: 🔍 Install PHPCS and PHPCompatibility
        run: |
          composer global require --dev dealerdirect/phpcodesniffer-composer-installer
          composer global require phpcompatibility/php-compatibility

      - name: 🧪 Run PHPCompatibility scan
        run: |
          ~/.composer/vendor/bin/phpcs build/$PLUGIN_SLUG \
            --standard=PHPCompatibility \
            --report=full \
            --runtime-set testVersion 7.4-8.2

      - name: 📦 Create ZIP archive
        run: |
          cd build
          zip -r ../$PLUGIN_SLUG.${RELEASE_TAG}.zip $PLUGIN_SLUG

      - name: 🚀 Upload release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          name: Revalidate for Vercel ${{ env.RELEASE_TAG }}
          tag_name: ${{ env.RELEASE_TAG }}
          files: revalidate-for-vercel.${{ env.RELEASE_TAG }}.zip
          body: |
            ✅ Automated release from GitHub Actions
            See the changelog and documentation in README.md 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
